version: "2"
services:
  grpcaccountsservice:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    hostname: "grpcaccountsservice"
    container_name: grpcaccountsservice
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=dbMysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=Microservices3
    volumes:
      - ./:/home/node/app
    ports:
      - "5001:5001"
    expose:
      - "5001"
    command: "npm start"
    networks:
      - shopnetwork

networks:
  shopnetwork:
